[package]
name = "mqtt_typed_client"
version = "0.1.0"
edition = "2021"
description = "A typed MQTT client library with pattern-based routing and automatic subscription management"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/mqtt_typed_client"
keywords = ["mqtt", "async", "typed", "client", "iot"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[dependencies]
arcstr = "1.2.0"
async-trait = "0.1.88"
bincode = "2.0.1"
bytes = "1.10.1"
futures = "0.3.31"
lru = "0.14.0"
rumqttc = { version = "0.24.0", features = ["url"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
time = { version = "0.3.41", features = ["formatting"] }
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
