use std::fs;

use quote::ToTokens;
use regex::Regex;
use syn::{
	LitStr, Token,
	parse::{Parse, ParseStream},
};

/// Input parsing for the macro
/// Supports: include_md_transformed!("path/to/file.md")
/// Or: include_md_transformed!("path/to/file.md", transform = "examples")
pub struct TransformInput {
	pub path: LitStr,
	pub transform_type: Option<TransformType>,
}

#[derive(Debug, Clone, Copy)]
pub enum TransformType {
	Examples,
	Readme,
}

impl Parse for TransformInput {
	fn parse(input: ParseStream) -> syn::Result<Self> {
		let path: LitStr = input.parse()?;

		let transform_type = if input.peek(Token![,]) {
			input.parse::<Token![,]>()?;

			// Parse "transform = "type""
			let ident: syn::Ident = input.parse()?;
			if ident != "transform" {
				return Err(syn::Error::new(
					ident.span(),
					"expected 'transform'",
				));
			}

			input.parse::<Token![=]>()?;
			let transform_lit: LitStr = input.parse()?;

			let transform_str = transform_lit.value();
			Some(match transform_str.as_str() {
				| "examples" => TransformType::Examples,
				| "readme" => TransformType::Readme,
				| _ => {
					return Err(syn::Error::new(
						transform_lit.span(),
						"transform type must be 'examples' or 'readme'",
					));
				}
			})
		} else {
			None
		};

		Ok(TransformInput {
			path,
			transform_type,
		})
	}
}

pub fn process_markdown(
	input: &TransformInput,
) -> syn::Result<proc_macro2::TokenStream> {
	let path_str = input.path.value();

	// Resolve path relative to CARGO_MANIFEST_DIR
	let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|_| {
		syn::Error::new(input.path.span(), "CARGO_MANIFEST_DIR not set")
	})?;

	let full_path = std::path::Path::new(&manifest_dir).join(&path_str);

	// Read file content
	let content = fs::read_to_string(&full_path).map_err(|e| {
		syn::Error::new(
			input.path.span(),
			format!("Failed to read file '{}': {}", full_path.display(), e),
		)
	})?;

	// Transform based on type
	let transformed = match input.transform_type {
		| Some(TransformType::Examples) => transform_examples_links(&content),
		| Some(TransformType::Readme) => transform_readme_links(&content),
		| None => content, // No transformation
	};

	// Return as string literal
	Ok(transformed.to_token_stream())
}

/// Transform example links: [file.rs](path#example) -> [file.rs](example_module/index.html)
fn transform_examples_links(content: &str) -> String {
	let header = "<!-- \nTHIS FILE IS AUTO-GENERATED\n\nDO NOT EDIT THIS FILE \
	              DIRECTLY!\nInstead, edit the source markdown and \
	              rebuild.\n-->\n\n";

	// Regex to match links with #example marker
	let re = Regex::new(r"\[([^]]+\.rs)\]\([^)]*#example\)").unwrap();

	let transformed = re.replace_all(content, |caps: &regex::Captures| {
		let filename = &caps[1];
		let module_name = filename.replace(".rs", "");
		format!("[{filename}](example_{module_name}/index.html)")
	});

	format!("{}{}", header, transformed)
}

/// Transform readme links: [examples/](examples/) -> [`crate::examples`]
fn transform_readme_links(content: &str) -> String {
	let header = "<!-- \nTHIS FILE IS AUTO-GENERATED\n\nDO NOT EDIT THIS FILE \
	              DIRECTLY!\nInstead, edit the source markdown and \
	              rebuild.\n-->\n\n";

	let re = Regex::new(r"\[examples/\]\(examples/\)").unwrap();
	let transformed = re.replace_all(content, "[`crate::examples`]");

	format!("{}{}", header, transformed)
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_transform_examples_links() {
		let input =
			"Check [example.rs](./examples/example.rs#example) for details";
		let output = transform_examples_links(input);
		assert!(output.contains("[example.rs](example_example/index.html)"));
	}

	#[test]
	fn test_transform_readme_links() {
		let input = "See [examples/](examples/) for more";
		let output = transform_readme_links(input);
		assert!(output.contains("[`crate::examples`]"));
	}
}
